"""baseline schema

Revision ID: b6f7436eccf6
Revises: 
Create Date: 2025-08-16 08:55:57.555497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f7436eccf6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_mobile', sa.String(length=20), nullable=True),
    sa.Column('visitor_id', sa.String(length=64), nullable=True),
    sa.Column('scope', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('escalated', sa.Boolean(), nullable=True),
    sa.Column('assigned_agent', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_session'))
    )
    with op.batch_alter_table('chat_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_session_user_mobile'), ['user_mobile'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_session_visitor_id'), ['visitor_id'], unique=False)

    op.create_table('company_loan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('loan_amount', sa.Float(), nullable=False),
    sa.Column('processing_fee', sa.Float(), nullable=False),
    sa.Column('gst', sa.Float(), nullable=False),
    sa.Column('total_processing_fee', sa.Float(), nullable=False),
    sa.Column('total_disbursement', sa.Float(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_loan'))
    )
    op.create_table('expenditure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('expenditure_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('comments', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expenditure'))
    )
    op.create_table('loan_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('stockist_name', sa.String(length=100), nullable=False),
    sa.Column('warehouse', sa.String(length=100), nullable=True),
    sa.Column('commodity', sa.String(length=30), nullable=True),
    sa.Column('loan_type', sa.String(length=30), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loan_data'))
    )
    op.create_table('loan_repayment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loan_repayment'))
    )
    op.create_table('margin_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('stockist_name', sa.String(length=100), nullable=False),
    sa.Column('warehouse', sa.String(length=100), nullable=False),
    sa.Column('commodity', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_margin_data'))
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('seller_name', sa.String(length=100), nullable=False),
    sa.Column('warehouse', sa.String(length=100), nullable=False),
    sa.Column('commodity', sa.String(length=50), nullable=False),
    sa.Column('banking_name', sa.String(length=100), nullable=False),
    sa.Column('account_number', sa.String(length=30), nullable=False),
    sa.Column('ifsc', sa.String(length=20), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('bank_reference', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment'))
    )
    op.create_table('purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('rst_no', sa.String(length=50), nullable=True),
    sa.Column('warehouse', sa.String(length=100), nullable=True),
    sa.Column('seller_name', sa.String(length=100), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('commodity', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('reduction', sa.Float(), nullable=True),
    sa.Column('net_qty', sa.Float(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('handling', sa.Float(), nullable=True),
    sa.Column('net_cost', sa.Float(), nullable=True),
    sa.Column('quality', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase')),
    sa.UniqueConstraint('rst_no', 'warehouse', name='uix_rstno_warehouse')
    )
    op.create_table('seller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('mobile', sa.String(length=15), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('banking_name', sa.String(length=100), nullable=True),
    sa.Column('account_number', sa.String(length=30), nullable=True),
    sa.Column('ifsc_code', sa.String(length=20), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seller')),
    sa.UniqueConstraint('mobile', name=op.f('uq_seller_mobile'))
    )
    op.create_table('stock_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rst_no', sa.String(length=50), nullable=False),
    sa.Column('warehouse', sa.String(length=120), nullable=False),
    sa.Column('stockist_name', sa.String(length=120), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('commodity', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('reduction', sa.Float(), nullable=True),
    sa.Column('net_qty', sa.Float(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('handling', sa.Float(), nullable=True),
    sa.Column('net_cost', sa.Float(), nullable=True),
    sa.Column('quality', sa.String(length=40), nullable=True),
    sa.Column('kind_of_stock', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_data'))
    )
    op.create_table('stock_exit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('warehouse', sa.String(length=100), nullable=False),
    sa.Column('stockist_name', sa.String(length=100), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('commodity', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('reduction', sa.Float(), nullable=False),
    sa.Column('net_qty', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('handling', sa.Float(), nullable=False),
    sa.Column('net_cost', sa.Float(), nullable=False),
    sa.Column('quality', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_exit'))
    )
    op.create_table('stockist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('mobile', sa.String(length=15), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('banking_name', sa.String(length=100), nullable=True),
    sa.Column('account_number', sa.String(length=30), nullable=True),
    sa.Column('ifsc_code', sa.String(length=20), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stockist')),
    sa.UniqueConstraint('mobile', name=op.f('uq_stockist_mobile'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('mobile', sa.String(length=15), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('mobile', name=op.f('uq_user_mobile'))
    )
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('sender_type', sa.String(length=10), nullable=False),
    sa.Column('sender_id', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], name=op.f('fk_chat_message_session_id_chat_session')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_message'))
    )
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_message_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_message_session_id'))

    op.drop_table('chat_message')
    op.drop_table('user')
    op.drop_table('stockist')
    op.drop_table('stock_exit')
    op.drop_table('stock_data')
    op.drop_table('seller')
    op.drop_table('purchase')
    op.drop_table('payment')
    op.drop_table('margin_data')
    op.drop_table('loan_repayment')
    op.drop_table('loan_data')
    op.drop_table('expenditure')
    op.drop_table('company_loan')
    with op.batch_alter_table('chat_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_session_visitor_id'))
        batch_op.drop_index(batch_op.f('ix_chat_session_user_mobile'))

    op.drop_table('chat_session')
    # ### end Alembic commands ###
